###
GET http://localhost:5000/api/departments

###

GET http://localhost:5000/api/employee

###

POST http://localhost:5000/api/employee
Content-Type: application/json

{
   "name": "John",
   "email": "john1@gmail.com",
   "department": "68d8f4abc739956a51ab8cda",
   "employmentDate": "11/11/2023",
   "employeeID": "UUID0001",
   "dateOfBirth": "10/10/1996",
   "idNumber": "1234567890",
   "address": "Yangon, Myanmar"
}

###

GET http://localhost:5000/api/employee/68d90e4b87c83a41c59038c7

###

PUT http://localhost:5000/api/employee/68d90e4b87c83a41c59038c7
Content-Type: application/json

{
    "employeeID": "UUID0002"
}

###
DELETE http://localhost:5000/api/employee/68d911acbf9cbac0f8cd5749