GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "test",
    "email": "test1@gmail.com",
    "password": "test"
}

###
PUT http://localhost:5000/api/users/68d4e4ebd5813d1fab1a5ada
Content-Type: application/json

{
    "name": "test1"
}

###
DELETE http://localhost:5000/api/users/68d4e5d35dd54057512bdb5a

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###
POST http://localhost:5000/api/logout
