###
GET http://localhost:5000/api/departments

###
POST http://localhost:5000/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDY1NzM4ZDc2ZDYxMGZkZDg2ZTU2OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTExOTU5NCwiZXhwIjoxNzU5MjA1OTk0fQ.WF8XdBfQr7U5_-F6HKX_U2ek5JsyU-hMERMXsCTqzQI

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
   "email": "test@gmail.com",
   "password": "test"
}

###

GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDY1NzM4ZDc2ZDYxMGZkZDg2ZTU2OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTExOTU5NCwiZXhwIjoxNzU5MjA1OTk0fQ.WF8XdBfQr7U5_-F6HKX_U2ek5JsyU-hMERMXsCTqzQI

###

POST http://localhost:5000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDY1NzM4ZDc2ZDYxMGZkZDg2ZTU2OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTExOTU5NCwiZXhwIjoxNzU5MjA1OTk0fQ.WF8XdBfQr7U5_-F6HKX_U2ek5JsyU-hMERMXsCTqzQI

{
   "name": "Jotestgjn",
   "email": "johflghsn1@gmail.com",
   "password": "password"
}

###

GET http://localhost:5000/api/employee

###

PUT http://localhost:5000/api/employee/68d90e4b87c83a41c59038c7
Content-Type: application/json

{
    "employeeID": "UUID0002"
}

###
DELETE http://localhost:5000/api/users/68da13733bc12ffd72519e09
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDY1NzM4ZDc2ZDYxMGZkZDg2ZTU2OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTExOTU5NCwiZXhwIjoxNzU5MjA1OTk0fQ.WF8XdBfQr7U5_-F6HKX_U2ek5JsyU-hMERMXsCTqzQI


###
GET http://localhost:5000/api/attendance

###
POST http://localhost:5000/api/attendance
Content-Type: application/json


###
DELETE http://localhost:5000/api/attendance/68db5c78d0d34849a1b5c23f

###
GET https://workplace-w264.onrender.com/api/attendance-sheets

###
GET http://localhost:5000/api/attendance-sheets

###
POST http://localhost:5000/workplace/employee
Content-Type: application/json

{
   "email": "ko@gmail.com",
   "token": "9Ri7VDYuKs"
}